apiVersion: v1
kind: ConfigMap
metadata:
  name: ocis-configs
{{- $ocisprevious := lookup "v1" "ConfigMaps" .Release.Namespace "ocis-configs" }}
{{- $ocis_system_user_id := "" }}
{{- $ocis_admin_user_id := "" }}
{{- $graph_application_id := "" }}
{{- $storage_users_mount_id := "" }}
data:
  {{- if $ocisprevious}}
  OCIS_SYSTEM_USER_ID: {{ index $ocisprevious.data "OCIS_SYSTEM_USER_ID" }}
  OCIS_ADMIN_USER_ID: {{ index $ocisprevious.data "OCIS_ADMIN_USER_ID" }}
  GRAPH_APPLICATION_ID: {{ index $ocisprevious.data "GRAPH_APPLICATION_ID" }}
  STORAGE_USERS_MOUNT_ID: {{ index $ocisprevious.data "STORAGE_USERS_MOUNT_ID" }}
  GATEWAY_STORAGE_USERS_MOUNT_ID: {{ index $ocisprevious.data "GATEWAY_STORAGE_USERS_MOUNT_ID" }}
  {{- else }}
  {{- $ocis_system_user_id := uuidv4 }}
  {{- $ocis_admin_user_id := uuidv4 }}
  {{- $graph_application_id := uuidv4 }}
  {{- $storage_users_mount_id := uuidv4 }}
  OCIS_SYSTEM_USER_ID: {{ $ocis_system_user_id }}
  OCIS_ADMIN_USER_ID: {{ $ocis_admin_user_id }}
  GRAPH_APPLICATION_ID: {{ $graph_application_id }}
  STORAGE_USERS_MOUNT_ID: {{ $storage_users_mount_id }}
  GATEWAY_STORAGE_USERS_MOUNT_ID: {{ $storage_users_mount_id }}
  {{- end }}