apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ocis-secrets
{{- $ocisprevious := lookup "v1" "Secret" .Release.Namespace "ocis-secrets" }}
{{- $ocis_jwt_secret := "" }}
{{- $storage_transfer_secret := "" }}
{{- $ocis_machine_auth_api_Key := "" }}
{{- $ocis_system_user_api_key := "" }}
{{- $idm_admin_password := "" }}
{{- $ldap_bind_password := "" }}
{{- $thumbnails_transfer_token := "" }}
data:
  {{- if $ocisprevious}}
  OCIS_JWT_SECRET: {{ index $ocisprevious.data "OCIS_JWT_SECRET" }}
  STORAGE_TRANSFER_SECRET: {{ index $ocisprevious.data "STORAGE_TRANSFER_SECRET" }}
  OCIS_MACHINE_AUTH_API_KEY: {{ index $ocisprevious.data "OCIS_MACHINE_AUTH_API_KEY" }}
  OCIS_SYSTEM_USER_API_KEY: {{ index $ocisprevious.data "OCIS_SYSTEM_USER_API_KEY" }}
  IDM_ADMIN_PASSWORD: {{ index $ocisprevious.data "IDM_ADMIN_PASSWORD" }}
  LDAP_BIND_PASSWORD: {{ index $ocisprevious.data "LDAP_BIND_PASSWORD" }}
  THUMBNAILS_TRANSFER_TOKEN: {{ index $ocisprevious.data "THUMBNAILS_TRANSFER_TOKEN" }}
  {{- else }}
  {{- $ocis_jwt_secret := randAlphaNum 32 }}
  {{- $storage_transfer_secret := randAlphaNum 32 }}
  {{- $ocis_machine_auth_api_Key := randAlphaNum 32 }}
  {{- $ocis_system_user_api_key := randAlphaNum 32 }}
  {{- $idm_admin_password := randAlphaNum 32 }}
  {{- $ldap_bind_password := randAlphaNum 32 }}
  {{- $thumbnails_transfer_token := randAlphaNum 32 }}
  OCIS_JWT_SECRET: {{ $ocis_jwt_secret | b64enc }}
  STORAGE_TRANSFER_SECRET: {{ $storage_transfer_secret | b64enc }}
  OCIS_MACHINE_AUTH_API_KEY: {{ $ocis_machine_auth_api_Key | b64enc }}
  OCIS_SYSTEM_USER_API_KEY: {{ $ocis_system_user_api_key | b64enc }}
  IDM_ADMIN_PASSWORD: {{ $idm_admin_password | b64enc }}
  LDAP_BIND_PASSWORD: {{ $ldap_bind_password | b64enc }}
  THUMBNAILS_TRANSFER_TOKEN: {{ $thumbnails_transfer_token | b64enc }}
  {{- end }}
